services:
  mongo:
    image: mongo:8.0.15
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-reflash}
    command: --replSet rs0 --bind_ip_all
    volumes:
      - ./init_replica.js:/docker-entrypoint-initdb.d/00init_replica.js
      - mongo-data:/data/db

volumes:
  mongo-data:
