name: Package Mobile App

on:
  pull_request:
    branches:
      - main
    paths:
      - "mobile-app/**"
      - "shared/**"
  workflow_call:
    inputs:
      version:
        description: "Version of the app to build"
        default: "0.0.0"
        required: false
        type: string
    secrets:
      EXPO_TOKEN:
        description: "Expo access token for EAS Build"
        required: true

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Change version
        if: ${{ inputs.version != '0.0.0' }}
        working-directory: ./mobile-app
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Build Android APK
        working-directory: ./mobile-app
        run: eas build --platform android --profile preview --non-interactive --local --output ./mobile-app-${{ inputs.version || '0.0.0' }}.apk

      - name: Build Android AAB
        working-directory: ./mobile-app
        run: eas build --platform android --profile production --non-interactive --local --output ./mobile-app-${{ inputs.version || '0.0.0' }}.aab

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-app-${{ inputs.version || '0.0.0' }}
          path: |
            mobile-app/mobile-app-${{ inputs.version || '0.0.0' }}.apk
            mobile-app/mobile-app-${{ inputs.version || '0.0.0' }}.aab
          if-no-files-found: error
