name: Package Mobile App

on:
  pull_request:
    branches:
      - main
    paths:
      - "mobile-app/**"
      - "shared/**"
  push:
    branches:
      - main
    paths:
      - "mobile-app/**"
      - "shared/**"
  workflow_call:
    inputs:
      version:
        description: "Version of the app to build"
        default: "0.0.0"
        required: false
        type: string

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Change version
        if: ${{ inputs.version != '0.0.0' }}
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Export Expo Bundle
        run: npx expo export

      - name: Zip Bundle
        run: |
          cd dist
          zip -r ../mobile-app-${{ inputs.version }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobile-app-${{ inputs.version }}.zip
          path: mobile-app/mobile-app-${{ inputs.version }}.zip
          if-no-files-found: error
