name: Package Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the plugin to build"
        default: "0.0.0"
        required: false
        type: string
  pull_request:
    branches:
      - main
    paths:
      - "browser-extension/**"
      - ".github/workflows/package.extension.yml"
  workflow_call:
    inputs:
      version:
        description: "Version of the plugin to build"
        required: false
        type: string
  
env:
  VERSION: ${{ inputs.version || '0.0.0' }}

jobs:
  build:
    uses: ./.github/workflows/build.extension.yml
    with:
      version: ${{ inputs.version }}

  package:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./browser-extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: browser-extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: browser-extension/build

      - name: Package extension
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: extension-${{ env.VERSION }}
          path: browser-extension/build/**/*.zip
          if-no-files-found: error
