name: Package Mobile App

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the app to build"
        default: "0.0.0"
        required: false
        type: string
      android_build_apk:
        description: "Andoid build apk"
        default: true
        required: false
        type: boolean
      android_build_aab:
        description: "Andoid build aab"
        default: false
        required: false
        type: boolean
  pull_request:
    branches:
      - main
    paths:
      - "mobile-app/**"
      - "shared/**"
      - ".github/workflows/package.mobile.yml"
  workflow_call:
    inputs:
      version:
        description: "Version of the app to build"
        required: false
        type: string
      android_build_apk:
        description: "Andoid build apk"
        required: false
        type: boolean
      android_build_aab:
        description: "Andoid build aab"
        required: false
        type: boolean

env:
  ANDROID_BUILD_APK: ${{ inputs.android_build_apk || true }}
  ANDROID_BUILD_AAB: ${{ inputs.android_build_aab || false }}
  VERSION: ${{ inputs.version || '0.0.0' }}

jobs:
  build:
    uses: ./.github/workflows/build.mobile.yml

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install dependencies
        run: |
          npm ci
          cd mobile-app && npm install --legacy-peer-deps

      - name: Change version
        if: ${{ env.VERSION != '0.0.0' }}
        working-directory: ./mobile-app
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Prebuild Android
        working-directory: ./mobile-app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx expo prebuild --platform android

      - name: Configure Keystore
        working-directory: ./mobile-app/android
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore
          echo "storeFile=release.keystore" >> gradle.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> gradle.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> gradle.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> gradle.properties

      - name: Build Android APK
        if: ${{ env.ANDROID_BUILD_APK }}
        working-directory: ./mobile-app/android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Build Android AAB
        if: ${{ env.ANDROID_BUILD_AAB }}
        working-directory: ./mobile-app/android
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Upload Android APK
        if: ${{ env.ANDROID_BUILD_APK }}
        uses: actions/upload-artifact@v6
        with:
          name: mobile-app-${{ env.VERSION || '0.0.0' }}
          path: mobile-app/android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Upload Android AAB
        if: ${{ env.ANDROID_BUILD_AAB }}
        uses: actions/upload-artifact@v6
        with:
          name: mobile-app-${{ env.VERSION || '0.0.0' }}
          path: mobile-app/android/app/build/outputs/bundle/release/*.aab
          if-no-files-found: error
